app completed

diff --git a/project/php/Dockerfile b/project/php/Dockerfile
--- a/project/php/Dockerfile
+++ b/project/php/Dockerfile
@@ -11,10 +11,18 @@ RUN docker-php-ext-install pdo pdo_mysql \
     && pecl install redis && docker-php-ext-enable redis
 
 # Копирование файлов проекта
-COPY composer.json /var/www/html/composer.json
-COPY index.php /var/www/html/index.php
-COPY src/ /var/www/html/src/
+COPY php/composer.json /var/www/html/composer.json
+COPY public/index.php /var/www/html/public/index.php
+COPY php/src/ /var/www/html/src/
+
+# Создание директории public, если не существует
+RUN mkdir -p /var/www/html/public
 
 # Установка зависимостей Composer
-WORKDIR /var/www/html
+WORKDIR /var/www/html/
 RUN composer install --no-interaction --optimize-autoloader --verbose || { echo "Composer install failed"; exit 1; }
+RUN composer dump-autoload || { echo "Composer install failed"; exit 1; }
+
+# Установка прав доступа
+RUN chown -R www-data:www-data /var/www/html
+RUN chmod -R 755 /var/www/html
